import { db } from '@/db';
import { detectionJobs } from '@/db/schema';

async function main() {
    const now = new Date();
    
    const getDateDaysAgo = (daysAgo: number): string => {
        const date = new Date(now);
        date.setDate(date.getDate() - daysAgo);
        return date.toISOString();
    };

    const sampleJobs = [
        {
            jobId: 'job-001-video-pending',
            organizationId: 1,
            status: 'pending',
            contentType: 'video',
            fileUrl: 'https://storage.example.com/videos/interview-2024.mp4',
            fileSizeBytes: 15728640,
            tierReached: null,
            confidenceScore: null,
            prediction: null,
            processingTimeMs: null,
            errorMessage: null,
            metadata: {},
            createdAt: getDateDaysAgo(2),
            updatedAt: getDateDaysAgo(2),
        },
        {
            jobId: 'job-002-image-completed',
            organizationId: 2,
            status: 'completed',
            contentType: 'image',
            fileUrl: 'https://storage.example.com/images/profile-photo.jpg',
            fileSizeBytes: 2097152,
            tierReached: 3,
            confidenceScore: 0.94,
            prediction: 'deepfake',
            processingTimeMs: 2340,
            errorMessage: null,
            metadata: { source: 'upload' },
            createdAt: getDateDaysAgo(5),
            updatedAt: getDateDaysAgo(5),
        },
        {
            jobId: 'job-003-audio-processing',
            organizationId: 1,
            status: 'processing',
            contentType: 'audio',
            fileUrl: 'https://storage.example.com/audio/voice-sample.mp3',
            fileSizeBytes: 5242880,
            tierReached: 1,
            confidenceScore: 0.72,
            prediction: null,
            processingTimeMs: null,
            errorMessage: null,
            metadata: {},
            createdAt: getDateDaysAgo(1),
            updatedAt: getDateDaysAgo(0),
        },
        {
            jobId: 'job-004-video-completed',
            organizationId: 3,
            status: 'completed',
            contentType: 'video',
            fileUrl: 'https://storage.example.com/videos/news-clip.mp4',
            fileSizeBytes: 31457280,
            tierReached: 4,
            confidenceScore: 0.98,
            prediction: 'authentic',
            processingTimeMs: 8750,
            errorMessage: null,
            metadata: { priority: 'high' },
            createdAt: getDateDaysAgo(8),
            updatedAt: getDateDaysAgo(8),
        },
        {
            jobId: 'job-005-image-failed',
            organizationId: 2,
            status: 'failed',
            contentType: 'image',
            fileUrl: 'https://storage.example.com/images/corrupted.jpg',
            fileSizeBytes: 1048576,
            tierReached: 1,
            confidenceScore: null,
            prediction: null,
            processingTimeMs: 450,
            errorMessage: 'File format not supported',
            metadata: {},
            createdAt: getDateDaysAgo(3),
            updatedAt: getDateDaysAgo(3),
        },
        {
            jobId: 'job-006-video-completed',
            organizationId: 4,
            status: 'completed',
            contentType: 'video',
            fileUrl: 'https://storage.example.com/videos/ceo-statement.mp4',
            fileSizeBytes: 20971520,
            tierReached: 2,
            confidenceScore: 0.89,
            prediction: 'authentic',
            processingTimeMs: 3200,
            errorMessage: null,
            metadata: {},
            createdAt: getDateDaysAgo(12),
            updatedAt: getDateDaysAgo(12),
        },
        {
            jobId: 'job-007-audio-completed',
            organizationId: 5,
            status: 'completed',
            contentType: 'audio',
            fileUrl: 'https://storage.example.com/audio/phone-call.wav',
            fileSizeBytes: 8388608,
            tierReached: 4,
            confidenceScore: 0.96,
            prediction: 'deepfake',
            processingTimeMs: 4560,
            errorMessage: null,
            metadata: { caller_id: 'unknown' },
            createdAt: getDateDaysAgo(7),
            updatedAt: getDateDaysAgo(7),
        },
        {
            jobId: 'job-008-image-completed',
            organizationId: 3,
            status: 'completed',
            contentType: 'image',
            fileUrl: 'https://storage.example.com/images/id-verification.png',
            fileSizeBytes: 3145728,
            tierReached: 3,
            confidenceScore: 0.91,
            prediction: 'uncertain',
            processingTimeMs: 2100,
            errorMessage: null,
            metadata: {},
            createdAt: getDateDaysAgo(15),
            updatedAt: getDateDaysAgo(15),
        },
        {
            jobId: 'job-009-video-pending',
            organizationId: 1,
            status: 'pending',
            contentType: 'video',
            fileUrl: 'https://storage.example.com/videos/conference-recording.mp4',
            fileSizeBytes: 52428800,
            tierReached: null,
            confidenceScore: null,
            prediction: null,
            processingTimeMs: null,
            errorMessage: null,
            metadata: {},
            createdAt: getDateDaysAgo(1),
            updatedAt: getDateDaysAgo(1),
        },
        {
            jobId: 'job-010-image-completed',
            organizationId: 2,
            status: 'completed',
            contentType: 'image',
            fileUrl: 'https://storage.example.com/images/social-post.jpg',
            fileSizeBytes: 1572864,
            tierReached: 2,
            confidenceScore: 0.86,
            prediction: 'authentic',
            processingTimeMs: 1800,
            errorMessage: null,
            metadata: { platform: 'twitter' },
            createdAt: getDateDaysAgo(10),
            updatedAt: getDateDaysAgo(10),
        },
        {
            jobId: 'job-011-audio-processing',
            organizationId: 5,
            status: 'processing',
            contentType: 'audio',
            fileUrl: 'https://storage.example.com/audio/podcast-episode.mp3',
            fileSizeBytes: 12582912,
            tierReached: 2,
            confidenceScore: 0.78,
            prediction: null,
            processingTimeMs: null,
            errorMessage: null,
            metadata: {},
            createdAt: getDateDaysAgo(4),
            updatedAt: getDateDaysAgo(0),
        },
        {
            jobId: 'job-012-video-completed',
            organizationId: 3,
            status: 'completed',
            contentType: 'video',
            fileUrl: 'https://storage.example.com/videos/advertisement.mp4',
            fileSizeBytes: 10485760,
            tierReached: 1,
            confidenceScore: 0.65,
            prediction: 'authentic',
            processingTimeMs: 1200,
            errorMessage: null,
            metadata: {},
            createdAt: getDateDaysAgo(20),
            updatedAt: getDateDaysAgo(20),
        },
        {
            jobId: 'job-013-image-completed',
            organizationId: 4,
            status: 'completed',
            contentType: 'image',
            fileUrl: 'https://storage.example.com/images/document-scan.tiff',
            fileSizeBytes: 4194304,
            tierReached: 4,
            confidenceScore: 0.99,
            prediction: 'deepfake',
            processingTimeMs: 3400,
            errorMessage: null,
            metadata: { document_type: 'passport' },
            createdAt: getDateDaysAgo(18),
            updatedAt: getDateDaysAgo(18),
        },
        {
            jobId: 'job-014-video-failed',
            organizationId: 1,
            status: 'failed',
            contentType: 'video',
            fileUrl: 'https://storage.example.com/videos/timeout-test.mp4',
            fileSizeBytes: 104857600,
            tierReached: null,
            confidenceScore: null,
            prediction: null,
            processingTimeMs: 30000,
            errorMessage: 'Processing timeout exceeded',
            metadata: {},
            createdAt: getDateDaysAgo(6),
            updatedAt: getDateDaysAgo(6),
        },
        {
            jobId: 'job-015-audio-completed',
            organizationId: 5,
            status: 'completed',
            contentType: 'audio',
            fileUrl: 'https://storage.example.com/audio/emergency-call.wav',
            fileSizeBytes: 6291456,
            tierReached: 3,
            confidenceScore: 0.93,
            prediction: 'authentic',
            processingTimeMs: 3800,
            errorMessage: null,
            metadata: { emergency_type: '911' },
            createdAt: getDateDaysAgo(25),
            updatedAt: getDateDaysAgo(25),
        },
    ];

    await db.insert(detectionJobs).values(sampleJobs);
    
    console.log('✅ Detection jobs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});